### ISSUE TITLE
Mixins

### ISSUE THREAD

**Issue by mmjaeger** [nelsonleite/foxgrid#1]
Hello
I was wondering whether you're planning to come up with some mixins so foxgrid could be used in a more unobtrusive way as well e.g.

.main {

@include columns(4);

}

**Comment by nelsonleite** [comment]
Hi
Yes, when I have the time I will work on that, thanks for bringin that up.

**Comment by nelsonleite** [comment]
You can now build columns semantically.

**Comment by mmjaeger** [comment]
Sounds great - thank you - I'll look into it

On Sun, Jun 5, 2016 at 7:21 AM, Nelson Leite notifications@github.com
wrote:

> Closed #1 https://github.com/nelsonleite/foxgrid/issues/1.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/nelsonleite/foxgrid/issues/1#event-682169299, or mute
> the thread
> https://github.com/notifications/unsubscribe/ABe4lGxAbWLigTaQcjuGuyTICkipgAO1ks5qIttOgaJpZM4Ip0N7
> .

## 

Marco M. Jaeger
http://net4visions.com
